import { prisma } from "@/lib/prisma";
import type { Prisma } from "@/generated/prisma/client";
import { PAGE_SIZES } from "@/lib/pagination";
import { fold } from "@/lib/search";
import { ownerLabel } from "@/lib/pet-label";
import { phoneSearchDigits } from "@/lib/phone";

export interface ListClientsArgs {
  clinicId: string;
  search?: string | null;
  includeArchived?: boolean;
  take?: number;
}

function buildClientWhere(args: {
  clinicId: string;
  search?: string | null;
  includeArchived?: boolean;
}): Prisma.ClientWhereInput {
  const term = args.search?.trim();
  return {
    clinicId: args.clinicId,
    ...(args.includeArchived ? {} : { archivedAt: null }),
    // One folded column instead of four `insensitive` columns.
    //
    // ILIKE folds case and nothing else, so "Ayse" did not find Ayşe and
    // the clinic was told, in as many words, that it has no such client.
    // `searchKey` is generated by Postgres as
    // `lower(immutable_unaccent(first last email phone))`, and the term
    // is folded here by the same rules (`lib/search.ts`,
    // `scripts/fold-parity.mjs`).
    //
    // Two things come with it and neither is an accident. The columns
    // are joined by spaces, so "ayse demir" finds a client whose first
    // and last name are stored apart -- the first thing anyone types,
    // and it never worked. And the search is indexed for the first time
    // (trigram GIN); four `contains` over separate columns could not be.
    ...(term ? termWhere(term) : {}),
  };
}

/**
 * A name matches the folded key; a number matches its digits as well,
 * however either side was written (pm B5: "0532 411" missed
 * "05324112233"). Both, not one or the other: "2024" may be part of an
 * e-mail address as easily as part of a number.
 */
export function termWhere(term: string): Prisma.ClientWhereInput {
  const digits = phoneSearchDigits(term);
  const byKey = { searchKey: { contains: fold(term) } };
  return digits ? { OR: [byKey, { phoneDigits: { contains: digits } }] } : byKey;
}

/**
 * Unpaginated list for select dropdowns, and whether there are more.
 *
 * Reads one row past the cap and throws it away. That one row is the
 * whole point: without it the list is indistinguishable from a complete
 * one, and a clinic past the cap is told nothing while its last hundred
 * clients quietly cannot be chosen.
 */
export async function listClients({
  take = PAGE_SIZES.DROPDOWN,
  ...args
}: ListClientsArgs) {
  const rows = await prisma.client.findMany({
    where: buildClientWhere(args),
    orderBy: [{ lastName: "asc" }, { firstName: "asc" }],
    take: take + 1,
    include: {
      _count: { select: { pets: { where: { archivedAt: null } } } },
    },
  });
  return { items: rows.slice(0, take), hasMore: rows.length > take };
}

export interface PagedClientsArgs extends Omit<ListClientsArgs, "take"> {
  page?: number;
  perPage?: number;
}

/** Paginated list, used by the clients table page. */
export async function listClientsPage({
  page = 1,
  perPage = PAGE_SIZES.DEFAULT,
  ...args
}: PagedClientsArgs) {
  const where = buildClientWhere(args);
  const [items, total] = await Promise.all([
    prisma.client.findMany({
      where,
      orderBy: [{ lastName: "asc" }, { firstName: "asc" }],
      skip: (page - 1) * perPage,
      take: perPage,
      include: {
        _count: { select: { pets: { where: { archivedAt: null } } } },
        // Two names beside the count, because eleven people called Ayşe
        // are told apart by their animals and not by their surnames.
        //
        // The same `where` as the count above, deliberately: a deceased
        // animal is still counted here, since somebody phoning about a
        // record they remember is exactly who this is for. Filtering
        // the names differently would make the row disagree with
        // itself -- two names from one set, "+N" from another.
        //
        // Ordered, and that is the part worth insisting on. An
        // unordered `take: 2` returns whichever two rows the database
        // finds convenient, which can differ between requests: the
        // same client would read "Pamuk, Duman" on one load and
        // "Duman, Tekir" on the next. A row that contradicts itself is
        // worse than a row that is merely terse, and worst of all in a
        // field used for recognition, where the vet is remembering
        // what it said last time.
        //
        // Alphabetical is the cheap stable answer, not the best one:
        // the two most recently seen animals would be the right two
        // for recognition, and that needs a visit join. Written down
        // so nobody mistakes "stable" for "correct".
        pets: {
          where: { archivedAt: null },
          select: { name: true },
          orderBy: { name: "asc" },
          take: 2,
        },
      },
    }),
    prisma.client.count({ where }),
  ]);
  return { items, total, page, perPage };
}

export async function getClientById(clinicId: string, id: string) {
  return prisma.client.findFirst({
    where: { id, clinicId },
    include: {
      pets: {
        where: { archivedAt: null },
        orderBy: { createdAt: "desc" },
        include: { customSpecies: { select: { name: true } } },
      },
      _count: { select: { visits: true, appointments: true, invoices: true } },
    },
  });
}

/**
 * Just enough of one client to label it in a picker. See `getPetLabel`
 * in `modules/pets/queries.ts` for why a picker needs this at all.
 */
export async function getClientLabel(clinicId: string, id: string) {
  const client = await prisma.client.findFirst({
    where: { id, clinicId },
    select: { firstName: true, lastName: true },
  });
  // The same helper the picker's own options are built with. This one
  // is handed to `Combobox` as `defaultLabel`, so a surname joined by
  // hand puts "Ayşe null" into a field the vet is reading as a settled
  // choice -- the very state this function exists to prevent.
  return client ? ownerLabel(client) : undefined;
}

export async function countClients(clinicId: string) {
  return prisma.client.count({ where: { clinicId, archivedAt: null } });
}

/**
 * Lightweight matches, used by the global command palette and — with a
 * larger `take` — by the pickers on the forms.
 *
 * The second caller is why the cap is a parameter rather than a constant
 * here: the palette wants five, a picker wants a screenful. Both want the
 * same query, and writing it twice is how the two would start disagreeing
 * about what "matches" means.
 */
export async function quickSearchClients(
  clinicId: string,
  term: string,
  // Annotated rather than inferred from the default: without it the
  // parameter's type is the literal 5 and the picker cannot ask for 20.
  take: number = PAGE_SIZES.COMMAND_PALETTE,
) {
  if (term.length < 2) return { items: [], hasMore: false };
  // Reads one row past the cap and throws it away, the same way
  // `listClients` does. That row is the whole answer to "is this all of
  // them": without it a search that returned exactly the cap and a
  // search that returned everything are the same array, and the picker
  // has to guess. It guessed by comparing the length to the cap, which
  // is the same fact written in two places -- and the two disagree the
  // day the cap moves.
  const rows = await prisma.client.findMany({
    where: buildClientWhere({ clinicId, search: term }),
    orderBy: [{ lastName: "asc" }, { firstName: "asc" }],
    take: take + 1,
    // Consent and phone travel with every search hit because the form
    // that reads them cannot tell where a client came from. A picker
    // fills itself from this list once the page's own list is capped,
    // and a warning that only works on the uncapped path is worse than
    // no warning: it is right often enough to be trusted and absent
    // exactly when the list got long.
    select: {
      id: true,
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      notificationsOptIn: true,
    },
  });
  return { items: rows.slice(0, take), hasMore: rows.length > take };
}
