// Comprehensive, curated breed catalog per built-in species.
//
// Names are Turkish-first (with the international name in parentheses where
// they differ), since the primary audience is Turkish veterinary clinics.
// The catalog only powers the searchable breed combobox on the pet form —
// `Pet.breed` itself stays free text, so clinics can enter anything and any
// breed they've used before is offered again via `listClinicBreedOptions`.
//
// Turkey-specific breeds (Kangal, Akbaş, Van Kedisi, Tekir, …) are included
// deliberately.

export const BREEDS: Record<string, readonly string[]> = {
  DOG: [
    "Kırma (Melez)",
    "Affenpinscher",
    "Afgan Tazısı (Afghan Hound)",
    "Airedale Terrier",
    "Akbaş",
    "Akita",
    "Aksaray Malaklısı",
    "Alaska Malamutu (Alaskan Malamute)",
    "Alman Çoban Köpeği (German Shepherd)",
    "Amerikan Bulldog",
    "Amerikan Cocker Spaniel",
    "Amerikan Pitbull Terrier",
    "Amerikan Staffordshire Terrier",
    "Anadolu Çoban Köpeği",
    "Avustralya Çoban Köpeği (Australian Shepherd)",
    "Avustralya Sığır Köpeği (Cattle Dog)",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Bedlington Terrier",
    "Belçika Malinois",
    "Belçika Tervueren",
    "Bernese Dağ Köpeği (Bernese Mountain Dog)",
    "Bichon Frise",
    "Bloodhound",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Brüksel Griffonu",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chow Chow",
    "Cocker Spaniel (İngiliz)",
    "Collie",
    "Coton de Tulear",
    "Çatalburun",
    "Dachshund (Sosis)",
    "Dalmaçyalı (Dalmatian)",
    "Danua (Great Dane)",
    "Doberman",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "English Setter",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "Fransız Bulldog",
    "Golden Retriever",
    "Gordon Setter",
    "Greyhound",
    "Havanese",
    "İngiliz Bulldog",
    "İrlanda Kurt Tazısı (Irish Wolfhound)",
    "İrlanda Setteri (Irish Setter)",
    "İtalyan Tazısı (Italian Greyhound)",
    "Jack Russell Terrier",
    "Japon Spitz",
    "Kangal",
    "Kaniş (Poodle) — Standart",
    "Kaniş (Poodle) — Minyatür",
    "Kaniş (Poodle) — Toy",
    "Keeshond",
    "Kerry Blue Terrier",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Leonberger",
    "Lhasa Apso",
    "Malta (Maltese)",
    "Maremma Çoban Köpeği",
    "Mastiff (İngiliz)",
    "Minyatür Pinscher",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Old English Sheepdog",
    "Papillon",
    "Pekinez (Pekingese)",
    "Pirene Dağ Köpeği (Great Pyrenees)",
    "Pointer",
    "Pomeranian",
    "Portekiz Su Köpeği",
    "Pug",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schnauzer — Minyatür",
    "Schnauzer — Standart",
    "Schnauzer — Dev (Giant)",
    "Scottish Terrier",
    "Shar Pei",
    "Shetland Çoban Köpeği (Sheltie)",
    "Shiba Inu",
    "Shih Tzu",
    "Sibirya Kurdu (Siberian Husky)",
    "Silky Terrier",
    "Springer Spaniel",
    "Staffordshire Bull Terrier",
    "Tibet Mastifi",
    "Tibet Terrier",
    "Vizsla (Macar)",
    "Weimaraner",
    "Welsh Corgi — Pembroke",
    "Welsh Corgi — Cardigan",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
    "Zerdava",
  ],
  CAT: [
    "Kırma (Melez)",
    "Tekir (Domestic Shorthair)",
    "Sarman",
    "Ankara Kedisi (Turkish Angora)",
    "Van Kedisi (Turkish Van)",
    "Habeş (Abyssinian)",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Chartreux",
    "Chinchilla",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Donskoy",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic Shorthair",
    "German Rex",
    "Havana Brown",
    "Himalaya (Himalayan)",
    "Japanese Bobtail",
    "Khao Manee",
    "Korat",
    "Kurilian Bobtail",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Nebelung",
    "Norveç Orman Kedisi (Norwegian Forest)",
    "Ocicat",
    "Oriental Shorthair",
    "İran / Pers (Persian)",
    "Peterbald",
    "Pixie-bob",
    "Ragamuffin",
    "Ragdoll",
    "Rus Mavisi (Russian Blue)",
    "Savannah",
    "Scottish Fold",
    "Scottish Straight",
    "Selkirk Rex",
    "Siyam (Siamese)",
    "Sibirya (Siberian)",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Toyger",
  ],
  BIRD: [
    "Muhabbet Kuşu (Budgerigar)",
    "Sultan Papağanı (Cockatiel)",
    "Sevda Papağanı (Lovebird)",
    "Kanarya (Canary)",
    "Jako (African Grey)",
    "Amazon Papağanı",
    "Ara Papağanı (Macaw)",
    "Kakadu (Cockatoo)",
    "Senegal Papağanı",
    "Keşiş Papağanı (Quaker/Monk)",
    "Yeşil Yanaklı Konur (Green-cheeked Conure)",
    "Güneş Konuru (Sun Conure)",
    "Forpus (Cep Papağanı)",
    "Lori Papağanı (Lorikeet)",
    "Pakistan Papağanı (Ringneck)",
    "İskender Papağanı (Alexandrine)",
    "Eklektus (Eclectus)",
    "Pionus",
    "Kaik Papağanı (Caique)",
    "Rozella (Rosella)",
    "Bourke Papağanı",
    "Zebra İspinozu (Zebra Finch)",
    "Bengal İspinozu (Society Finch)",
    "Gould İspinozu (Gouldian Finch)",
    "Java Serçesi (Java Sparrow)",
    "Saka (Goldfinch)",
    "İspinoz (Chaffinch)",
    "Hint Bülbülü (Red-whiskered Bulbul)",
    "Güvercin (Pigeon)",
    "Kumru",
    "Tavuk",
    "Horoz",
    "Ördek",
    "Kaz",
    "Hindi",
    "Bıldırcın (Quail)",
    "Sülün (Pheasant)",
    "Tavus Kuşu (Peafowl)",
    "Şahin / Doğan (Falconry)",
    "Baykuş (Owl)",
  ],
  RABBIT: [
    "Kırma (Melez)",
    "Hollanda Lop (Holland Lop)",
    "Mini Lop",
    "Fransız Lop (French Lop)",
    "İngiliz Lop (English Lop)",
    "Hollanda Cücesi (Netherland Dwarf)",
    "Cüce Hotot (Dwarf Hotot)",
    "Ankara / Angora Tavşanı — İngiliz",
    "Ankara / Angora Tavşanı — Fransız",
    "Rex",
    "Mini Rex",
    "Flaman Devi (Flemish Giant)",
    "Continental Giant",
    "Checkered Giant",
    "Himalayan",
    "Kaliforniya (Californian)",
    "Yeni Zelanda (New Zealand)",
    "Aslan Kafa (Lionhead)",
    "Harlequin",
    "Chinchilla Tavşanı",
    "English Spot",
    "Polish",
    "Tan",
    "Jersey Wooly",
    "Havana",
    "Silver Marten",
  ],
  RODENT: [
    "Suriye (Golden) Hamsteri",
    "Roborovski Cüce Hamsteri",
    "Campbell Cüce Hamsteri",
    "Sibirya (Winter White) Cüce Hamsteri",
    "Çin Hamsteri",
    "Gine Domuzu — Amerikan",
    "Gine Domuzu — Abyssinian",
    "Gine Domuzu — Peru",
    "Gine Domuzu — Sheltie",
    "Gine Domuzu — Skinny",
    "Chinchilla",
    "Degu",
    "Moğol Gerbili (Gerbil)",
    "Fare (Fancy Mouse)",
    "Sıçan (Fancy Rat)",
    "Dumbo Sıçan (Dumbo Rat)",
  ],
  REPTILE: [
    "Sakallı Ejder (Bearded Dragon)",
    "Leopar Gecko (Leopard Gecko)",
    "Tepeli Gecko (Crested Gecko)",
    "Tokay Gecko",
    "Yeşil İguana (Green Iguana)",
    "Yemen Bukalemunu (Veiled Chameleon)",
    "Panter Bukalemunu (Panther Chameleon)",
    "Mavi Dilli Skink (Blue-tongued Skink)",
    "Arjantin Tegusu (Argentine Tegu)",
    "Savannah Monitörü (Savannah Monitor)",
    "Su Ejderi (Chinese Water Dragon)",
    "Anol (Green Anole)",
    "Uromastyx (Dikenli Kuyruk)",
    "Mısır Yılanı (Corn Snake)",
    "Kral Yılanı (King Snake)",
    "Süt Yılanı (Milk Snake)",
    "Top Piton (Ball Python)",
    "Boa (Boa Constrictor)",
    "Kırmızı Yanaklı Su Kaplumbağası (Red-eared Slider)",
    "Sarı Yanaklı Su Kaplumbağası (Yellow-bellied Slider)",
    "Yunan Tosbağası (Greek Tortoise)",
    "Hermann Tosbağası (Hermann's Tortoise)",
    "Sulcata Kaplumbağası (African Spurred)",
    "Rus Tosbağası (Russian Tortoise)",
  ],
  FISH: [
    "Japon Balığı (Goldfish)",
    "Oranda",
    "Ranchu",
    "Black Moor",
    "Koi",
    "Beta (Siyam Savaş Balığı)",
    "Lepistes (Guppy)",
    "Endler Lepistesi",
    "Moli (Molly)",
    "Plati (Platy)",
    "Kılıçkuyruk (Swordtail)",
    "Neon Tetra",
    "Kardinal Tetra",
    "Tetra (diğer)",
    "Melek Balığı (Angelfish)",
    "Diskus (Discus)",
    "Çöpçü (Corydoras)",
    "Pleco (Vatoz/Zırhlı)",
    "Zebra Balığı (Danio)",
    "Kaplan Barbus (Tiger Barb)",
    "Cüce Gurami (Dwarf Gourami)",
    "Mavi Gurami (Blue Gourami)",
    "Oskar (Oscar)",
    "Malawi Ciklet",
    "Ciklet (diğer)",
    "Flowerhorn",
    "Arowana",
    "Rasbora",
    "Killifish",
  ],
  EXOTIC: [
    "Gelincik (Ferret)",
    "Pigme Kirpisi (African Pygmy Hedgehog)",
    "Şeker Planörü (Sugar Glider)",
    "Aksolotl (Axolotl)",
    "Pacman Kurbağası (Horned Frog)",
    "Ağaç Kurbağası (Tree Frog)",
    "Semender (Salamander/Newt)",
    "Tarantula",
    "Mini Domuz (Minipig)",
  ],
  OTHER: [],
};
