// Comprehensive breed catalog per built-in species.
//
// Sources cross-checked: FCI, AKC, UKC (dogs); TICA, CFA, FIFe (cats); common
// aviculture, herpetoculture and aquarium trade names; Turkish Ministry of
// Agriculture native-breed registries for dogs, cats, horses, cattle, sheep
// and goats. Names are Turkish-first with the international name in
// parentheses where they differ; Turkish native breeds are listed
// deliberately (Kangal, Akbaş, Van Kedisi, Rahvan, Akkaraman, Kıl Keçisi…).
//
// The catalog only powers the searchable breed combobox - `Pet.breed` stays
// free text, so clinics can enter anything, and every breed they've used is
// offered again via `listClinicBreedOptions`. Each list starts with the
// mixed/common entries vets pick most, then alphabetical.

export const BREEDS: Record<string, readonly string[]> = {
  DOG: [
    "Kırma (Melez)",
    "Sokak Köpeği",
    "Kangal",
    "Akbaş",
    "Alman Çoban Köpeği (German Shepherd)",
    "Golden Retriever",
    "Labrador Retriever",
    "Affenpinscher",
    "Afgan Tazısı (Afghan Hound)",
    "Airedale Terrier",
    "Akita (Japon)",
    "Amerikan Akita",
    "Aksaray Malaklısı",
    "Alaska Malamutu (Alaskan Malamute)",
    "Alaskan Klee Kai",
    "Amerikan Bulldog",
    "Amerikan Cocker Spaniel",
    "Amerikan Eskimo Köpeği",
    "Amerikan Pitbull Terrier",
    "Amerikan Staffordshire Terrier",
    "Amerikan Tüysüz Terrier",
    "Anadolu Çoban Köpeği",
    "Appenzeller Dağ Köpeği",
    "Avustralya Çoban Köpeği (Australian Shepherd)",
    "Avustralya Kelpie",
    "Avustralya Sığır Köpeği (Cattle Dog)",
    "Avustralya Terrier",
    "Azawakh",
    "Barbet",
    "Basenji",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belçika Groenendael",
    "Belçika Laekenois",
    "Belçika Malinois",
    "Belçika Tervueren",
    "Bergamasco",
    "Bernese Dağ Köpeği (Bernese Mountain Dog)",
    "Bichon Frise",
    "Biewer Terrier",
    "Bloodhound",
    "Boerboel",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi (Rus Tazısı)",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Briard",
    "Brittany Spaniel",
    "Brüksel Griffonu",
    "Bull Terrier",
    "Bull Terrier - Minyatür",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Catahoula Leopar Köpeği",
    "Cavalier King Charles Spaniel",
    "Cavapoo",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Çin Tepeli (Chinese Crested)",
    "Chow Chow",
    "Cirneco dell'Etna",
    "Clumber Spaniel",
    "Cocker Spaniel (İngiliz)",
    "Cockapoo",
    "Collie - Uzun Tüylü (Rough)",
    "Collie - Kısa Tüylü (Smooth)",
    "Coton de Tulear",
    "Curly-Coated Retriever",
    "Çatalburun",
    "Çek Kurt Köpeği (Czechoslovakian Vlcak)",
    "Dachshund (Sosis) - Standart",
    "Dachshund (Sosis) - Minyatür",
    "Dalmaçyalı (Dalmatian)",
    "Dandie Dinmont Terrier",
    "Danua (Great Dane)",
    "Doberman",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "Drentsche Patrijshond",
    "Dutch Shepherd (Hollanda Çoban Köpeği)",
    "English Setter",
    "English Toy Spaniel",
    "Entlebucher Dağ Köpeği",
    "Estrela Dağ Köpeği",
    "Eurasier",
    "Field Spaniel",
    "Fin Lapphund",
    "Fin Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier - Düz Tüylü",
    "Fox Terrier - Tel Tüylü",
    "Fransız Bulldog",
    "Alman Pinscher",
    "Alman Kısa Tüylü Pointer",
    "Alman Tel Tüylü Pointer",
    "Alman Spitz - Klein/Mittel",
    "Glen of Imaal Terrier",
    "Goldendoodle",
    "Gordon Setter",
    "Büyük İsviçre Dağ Köpeği",
    "Greyhound",
    "Harrier",
    "Havanese",
    "Hovawart",
    "Ibizan Hound",
    "İzlanda Çoban Köpeği",
    "İngiliz Bulldog",
    "İngiliz Foxhound",
    "İrlanda Kurt Tazısı (Irish Wolfhound)",
    "İrlanda Setteri (Irish Setter)",
    "İrlanda Terrier",
    "İrlanda Su Spanieli",
    "İtalyan Tazısı (Italian Greyhound)",
    "Jack Russell Terrier",
    "Japon Chin",
    "Japon Spitz",
    "Kafkas Çoban Köpeği (Caucasian Shepherd)",
    "Kai Ken",
    "Kaniş (Poodle) - Standart",
    "Kaniş (Poodle) - Minyatür",
    "Kaniş (Poodle) - Toy",
    "Karelian Bear Dog",
    "Keeshond",
    "Kerry Blue Terrier",
    "Kishu",
    "Komondor",
    "Kooikerhondje",
    "Kuvasz",
    "Labradoodle",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Leonberger",
    "Lhasa Apso",
    "Löwchen",
    "Malta (Maltese)",
    "Maltipoo",
    "Manchester Terrier",
    "Maremma Çoban Köpeği",
    "Mastiff (İngiliz)",
    "Minyatür Amerikan Çoban Köpeği",
    "Minyatür Pinscher",
    "Mudi",
    "Napoli Mastifi (Neapolitan Mastiff)",
    "Newfoundland",
    "Norfolk Terrier",
    "Norveç Buhund",
    "Norveç Elkhound",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Orta Asya Çoban Köpeği (Alabay)",
    "Otterhound",
    "Papillon",
    "Parson Russell Terrier",
    "Pekinez (Pekingese)",
    "Peru Tüysüz Köpeği",
    "Petit Basset Griffon Vendéen",
    "Grand Basset Griffon Vendéen",
    "Firavun Tazısı (Pharaoh Hound)",
    "Pirene Dağ Köpeği (Great Pyrenees)",
    "Pirene Çoban Köpeği",
    "Plott Hound",
    "Pointer (İngiliz)",
    "Polonya Ova Çoban Köpeği",
    "Pomeranian",
    "Pomsky",
    "Portekiz Podengo",
    "Portekiz Su Köpeği",
    "Presa Canario",
    "Pug",
    "Puli",
    "Pumi",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Rus Toy",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Sarplaninac",
    "Schipperke",
    "Schnauzer - Minyatür",
    "Schnauzer - Standart",
    "Schnauzer - Dev (Giant)",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shar Pei",
    "Shetland Çoban Köpeği (Sheltie)",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku",
    "Sibirya Kurdu (Siberian Husky)",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Slovak Cuvac",
    "Soft Coated Wheaten Terrier",
    "İspanyol Su Köpeği",
    "Spinone Italiano",
    "Springer Spaniel - İngiliz",
    "Springer Spaniel - Welsh",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Sussex Spaniel",
    "İsveç Vallhund",
    "Tayland Ridgeback",
    "Tibet Mastifi",
    "Tibet Spanieli",
    "Tibet Terrier",
    "Tornjak",
    "Tosa",
    "Toy Fox Terrier",
    "Treeing Walker Coonhound",
    "Türk Tazısı",
    "Vizsla (Macar) - Kısa Tüylü",
    "Vizsla (Macar) - Tel Tüylü",
    "Volpino Italiano",
    "Weimaraner",
    "Welsh Corgi - Pembroke",
    "Welsh Corgi - Cardigan",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintli (Meksika Tüysüz)",
    "Yakut Laika",
    "Yorkshire Terrier",
    "Zerdava",
  ],
  CAT: [
    "Kırma (Melez)",
    "Tekir (Domestic Shorthair)",
    "Uzun Tüylü Tekir (Domestic Longhair)",
    "Sokak Kedisi",
    "Sarman",
    "Ankara Kedisi (Turkish Angora)",
    "Van Kedisi (Turkish Van)",
    "Ege Kedisi (Aegean)",
    "British Shorthair",
    "Scottish Fold",
    "Habeş (Abyssinian)",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Arap Mau (Arabian Mau)",
    "Asian",
    "Australian Mist",
    "Balinese",
    "Bambino",
    "Bengal",
    "Birman",
    "Bombay",
    "Brezilya Shorthair",
    "British Longhair",
    "Burmese",
    "Burmilla",
    "California Spangled",
    "Chantilly-Tiffany",
    "Chartreux",
    "Chausie",
    "Cheetoh",
    "Chinchilla",
    "Colorpoint Shorthair",
    "Cornish Rex",
    "Kıbrıs Kedisi (Cyprus)",
    "Cymric",
    "Devon Rex",
    "Donskoy",
    "Dragon Li",
    "Dwelf",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic Shorthair",
    "Foldex",
    "German Rex",
    "Havana Brown",
    "Highlander",
    "Himalaya (Himalayan)",
    "Japanese Bobtail",
    "Javanese",
    "Khao Manee",
    "Kinkalow",
    "Korat",
    "Kurilian Bobtail",
    "Lambkin",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Minskin",
    "Minuet (Napoleon)",
    "Munchkin",
    "Nebelung",
    "Norveç Orman Kedisi (Norwegian Forest)",
    "Ocicat",
    "Ojos Azules",
    "Oriental Longhair",
    "Oriental Shorthair",
    "İran / Pers (Persian)",
    "Peterbald",
    "Pixie-bob",
    "Ragamuffin",
    "Ragdoll",
    "Rus Mavisi (Russian Blue)",
    "Savannah",
    "Scottish Straight",
    "Selkirk Rex",
    "Serengeti",
    "Siyam (Siamese)",
    "Sibirya (Siberian)",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Thai",
    "Tonkinese",
    "Toybob",
    "Toyger",
    "Ukrayna Levkoy",
    "York Chocolate",
  ],
  BIRD: [
    "Muhabbet Kuşu (Budgerigar)",
    "Sultan Papağanı (Cockatiel)",
    "Sevda Papağanı (Lovebird)",
    "Kanarya (Canary)",
    "Jako (African Grey)",
    "Timneh Jako",
    "Amazon Papağanı",
    "Ara Papağanı (Macaw)",
    "Kakadu (Cockatoo)",
    "Senegal Papağanı",
    "Meyer Papağanı",
    "Keşiş Papağanı (Quaker/Monk)",
    "Yeşil Yanaklı Konur (Green-cheeked Conure)",
    "Güneş Konuru (Sun Conure)",
    "Jenday Konuru",
    "Nanday Konuru",
    "Forpus (Cep Papağanı)",
    "Lori Papağanı (Lorikeet)",
    "Pakistan Papağanı (Ringneck)",
    "İskender Papağanı (Alexandrine)",
    "Eklektus (Eclectus)",
    "Pionus",
    "Kaik Papağanı (Caique)",
    "Rozella (Rosella)",
    "Bourke Papağanı",
    "Kral Papağanı (King Parrot)",
    "Hakiki Papağan (Hahn's Macaw)",
    "Zebra İspinozu (Zebra Finch)",
    "Bengal İspinozu (Society Finch)",
    "Gould İspinozu (Gouldian Finch)",
    "Java Serçesi (Java Sparrow)",
    "Saka (Goldfinch)",
    "İspinoz (Chaffinch)",
    "Florya (Greenfinch)",
    "Hint Bülbülü (Red-whiskered Bulbul)",
    "Mynah (Beo)",
    "Güvercin (Pigeon)",
    "Kumru",
    "Tavuk",
    "Horoz",
    "Ördek",
    "Kaz",
    "Hindi",
    "Bıldırcın (Quail)",
    "Sülün (Pheasant)",
    "Tavus Kuşu (Peafowl)",
    "Keklik",
    "Şahin (Hawk)",
    "Doğan (Falcon)",
    "Kartal (Eagle)",
    "Baykuş (Owl)",
    "Karga",
    "Saksağan",
    "Papağan (diğer)",
  ],
  RABBIT: [
    "Kırma (Melez)",
    "Hollanda Lop (Holland Lop)",
    "Mini Lop",
    "Fransız Lop (French Lop)",
    "İngiliz Lop (English Lop)",
    "Alman Lop",
    "Cüce Lop (Dwarf Lop)",
    "Hollanda Cücesi (Netherland Dwarf)",
    "Cüce Hotot (Dwarf Hotot)",
    "Blanc de Hotot",
    "Ankara / Angora Tavşanı - İngiliz",
    "Ankara / Angora Tavşanı - Fransız",
    "Ankara / Angora Tavşanı - Dev",
    "Ankara / Angora Tavşanı - Saten",
    "Rex",
    "Mini Rex",
    "Flaman Devi (Flemish Giant)",
    "Continental Giant",
    "Checkered Giant",
    "Himalayan",
    "Kaliforniya (Californian)",
    "Yeni Zelanda (New Zealand)",
    "Aslan Kafa (Lionhead)",
    "Harlequin",
    "Chinchilla Tavşanı",
    "English Spot",
    "Polish",
    "Britannia Petite",
    "Tan",
    "Jersey Wooly",
    "Havana",
    "Silver Marten",
    "Silver Fox",
    "Dutch",
    "Belçika Tavşanı (Belgian Hare)",
    "Beveren",
    "Cinnamon",
    "Florida White",
    "Lilac",
    "Palomino",
    "Saten (Satin)",
    "Mini Saten",
    "Thrianta",
    "Vienna",
  ],
  RODENT: [
    "Suriye (Golden) Hamsteri",
    "Suriye Hamsteri - Uzun Tüylü (Teddy Bear)",
    "Roborovski Cüce Hamsteri",
    "Campbell Cüce Hamsteri",
    "Sibirya (Winter White) Cüce Hamsteri",
    "Çin Hamsteri",
    "Gine Domuzu - Amerikan",
    "Gine Domuzu - Abyssinian",
    "Gine Domuzu - Peru",
    "Gine Domuzu - Sheltie (Silkie)",
    "Gine Domuzu - Skinny",
    "Gine Domuzu - Teddy",
    "Gine Domuzu - Texel",
    "Gine Domuzu - Coronet",
    "Gine Domuzu - Rex",
    "Gine Domuzu - Baldwin",
    "Chinchilla",
    "Degu",
    "Moğol Gerbili (Gerbil)",
    "Fare (Fancy Mouse)",
    "Sıçan (Fancy Rat)",
    "Dumbo Sıçan (Dumbo Rat)",
    "Rex Sıçan",
    "Tüysüz Sıçan (Hairless Rat)",
    "Sincap (Squirrel)",
    "Cüce Sincap (Chipmunk)",
    "Afrika Cüce Faresi",
    "Dikenli Fare (Spiny Mouse)",
    "Prairie Dog",
    "Kapibara",
  ],
  FERRET: [
    "Standart Gelincik",
    "Angora Gelincik",
    "Albino Gelincik",
    "Sable Gelincik",
    "Silver Gelincik",
    "Cinnamon Gelincik",
  ],
  REPTILE: [
    "Sakallı Ejder (Bearded Dragon)",
    "Rankin Ejderi",
    "Leopar Gecko (Leopard Gecko)",
    "Tepeli Gecko (Crested Gecko)",
    "Gargoyle Gecko",
    "Tokay Gecko",
    "Şişman Kuyruklu Gecko (Fat-tailed Gecko)",
    "Yeşil İguana (Green Iguana)",
    "Yemen Bukalemunu (Veiled Chameleon)",
    "Panter Bukalemunu (Panther Chameleon)",
    "Jackson Bukalemunu",
    "Mavi Dilli Skink (Blue-tongued Skink)",
    "Arjantin Tegusu (Argentine Tegu)",
    "Savannah Monitörü (Savannah Monitor)",
    "Ackie Monitör",
    "Su Ejderi (Chinese Water Dragon)",
    "Anol (Green Anole)",
    "Uromastyx (Dikenli Kuyruk)",
    "Basilisk",
    "Frilled Dragon (Yakalı Kertenkele)",
    "Mısır Yılanı (Corn Snake)",
    "Kral Yılanı (King Snake)",
    "Süt Yılanı (Milk Snake)",
    "Top Piton (Ball Python)",
    "Boa (Boa Constrictor)",
    "Kum Boası (Sand Boa)",
    "Gökkuşağı Boası (Rainbow Boa)",
    "Retiküle Piton",
    "Halı Pitonu (Carpet Python)",
    "Sıçan Yılanı (Rat Snake)",
    "Hognose Yılanı",
    "Garter Yılanı",
    "Kırmızı Yanaklı Su Kaplumbağası (Red-eared Slider)",
    "Sarı Yanaklı Su Kaplumbağası (Yellow-bellied Slider)",
    "Çizgili Boyunlu Kaplumbağa (Map Turtle)",
    "Musk Kaplumbağası",
    "Yunan Tosbağası (Greek Tortoise)",
    "Hermann Tosbağası (Hermann's Tortoise)",
    "Sulcata Kaplumbağası (African Spurred)",
    "Rus Tosbağası (Russian Tortoise)",
    "Leopar Kaplumbağası",
    "Kırmızı Ayaklı Kaplumbağa (Red-footed)",
    "Hint Yıldızlı Kaplumbağa",
    "Kutu Kaplumbağası (Box Turtle)",
    "Timsah (Kayman)",
  ],
  AMPHIBIAN: [
    "Aksolotl (Axolotl)",
    "Pacman Kurbağası (Horned Frog)",
    "Ağaç Kurbağası (Tree Frog)",
    "Beyaz Ağaç Kurbağası (White's Tree Frog)",
    "Kırmızı Gözlü Ağaç Kurbağası",
    "Zehirli Ok Kurbağası (Dart Frog)",
    "Afrika Cüce Kurbağası",
    "Afrika Pençeli Kurbağa (Xenopus)",
    "Boğa Kurbağası (Bullfrog)",
    "Kara Kurbağası (Toad)",
    "Kaplan Semenderi (Tiger Salamander)",
    "Ateş Semenderi (Fire Salamander)",
    "Ateş Karınlı Semender (Fire-bellied Newt)",
    "Ateş Karınlı Kurbağa (Fire-bellied Toad)",
    "Solucan Semender (Caecilian)",
  ],
  FISH: [
    "Japon Balığı (Goldfish)",
    "Oranda",
    "Ranchu",
    "Black Moor",
    "Ryukin",
    "Fantail",
    "Kuyruklu Yıldız (Comet)",
    "Shubunkin",
    "Koi",
    "Beta (Siyam Savaş Balığı)",
    "Lepistes (Guppy)",
    "Endler Lepistesi",
    "Moli (Molly)",
    "Balon Moli",
    "Plati (Platy)",
    "Kılıçkuyruk (Swordtail)",
    "Neon Tetra",
    "Kardinal Tetra",
    "Kara Neon Tetra",
    "Rummy Nose Tetra",
    "Kongo Tetrası",
    "Tetra (diğer)",
    "Melek Balığı (Angelfish)",
    "Diskus (Discus)",
    "Çöpçü (Corydoras)",
    "Pleco (Vatoz/Zırhlı)",
    "Ancistrus",
    "Otocinclus",
    "Zebra Balığı (Danio)",
    "Kaplan Barbus (Tiger Barb)",
    "Kiraz Barbus",
    "Cüce Gurami (Dwarf Gourami)",
    "Mavi Gurami (Blue Gourami)",
    "Bal Gurami (Honey Gourami)",
    "Öpüşen Gurami",
    "Oskar (Oscar)",
    "Malawi Ciklet",
    "Tanganyika Ciklet",
    "Amerikan Ciklet",
    "Ciklet (diğer)",
    "Flowerhorn",
    "Arowana",
    "Rasbora",
    "Killifish",
    "Fil Burunlu Balık (Elephant Nose)",
    "Cam Kedi Balığı (Glass Catfish)",
    "Sinodontis",
    "Yılan Balığı (Loach)",
    "Palyaço Loach",
    "Kuhli Loach",
    "Karides (Neocaridina)",
    "Karides (Caridina)",
    "Salyangoz (Nerite/Mystery)",
    "Palyaço Balığı (Clownfish)",
    "Tang (Cerrah Balığı)",
    "Damsel",
    "Kaya Balığı (Goby)",
    "Wrasse",
    "Deniz Atı (Seahorse)",
    "Mercan (Coral)",
  ],
  HORSE: [
    "Kırma (Melez)",
    "Arap Atı",
    "İngiliz Atı (Thoroughbred)",
    "Rahvan Atı",
    "Anadolu Yerli Atı",
    "Midilli (Pony)",
    "Shetland Midillisi",
    "Welsh Midillisi",
    "Haflinger",
    "Ahal Teke",
    "Andalus (PRE)",
    "Lusitano",
    "Lipizzan",
    "Friesian",
    "Quarter Horse",
    "Paint Horse",
    "Appaloosa",
    "Morgan",
    "Standardbred",
    "Trakehner",
    "Hanoverian",
    "Holsteiner",
    "Oldenburg",
    "Westphalian",
    "KWPN (Hollanda Sıcakkanlı)",
    "Selle Français",
    "Belçika Sıcakkanlı",
    "İrlanda Spor Atı",
    "Connemara",
    "Fjord",
    "Icelandic",
    "Percheron",
    "Clydesdale",
    "Shire",
    "Belçika Soğukkanlı",
    "Ardennes",
    "Karakaçan Eşeği",
    "Katır",
    "Eşek",
  ],
  CATTLE: [
    "Kırma (Melez)",
    "Holstein (Siyah Alaca)",
    "Simental",
    "Montofon (Brown Swiss)",
    "Jersey",
    "Angus",
    "Hereford",
    "Limousin",
    "Charolais",
    "Şarole (Charolais Melezi)",
    "Belçika Mavisi",
    "Yerli Kara",
    "Boz Irk",
    "Doğu Anadolu Kırmızısı",
    "Güney Anadolu Kırmızısı (Kilis)",
    "Yerli Güney Sarısı",
    "Zavot",
    "Sarı Alaca",
    "Kırmızı Alaca",
    "Guernsey",
    "Ayrshire",
    "Brahman",
    "Wagyu",
    "Galloway",
    "Highland (İskoç)",
    "Dexter",
    "Manda (Anadolu Mandası)",
    "Zebu",
  ],
  SHEEP: [
    "Kırma (Melez)",
    "Akkaraman",
    "Morkaraman",
    "Kıvırcık",
    "İvesi (Awassi)",
    "Sakız",
    "Dağlıç",
    "Karayaka",
    "Merinos (Türk Merinosu)",
    "Karacabey Merinosu",
    "Anadolu Merinosu",
    "Kangal Akkaraman",
    "Hemşin",
    "Tuj",
    "Norduz",
    "Herik",
    "Çine Çaparı",
    "Gökçeada Koyunu",
    "İmroz",
    "Karakaş",
    "Malya",
    "Ramlıç",
    "Tahirova",
    "Assaf",
    "Lacaune",
    "Suffolk",
    "Texel",
    "Dorper",
    "Ile de France",
    "Romanov",
  ],
  GOAT: [
    "Kırma (Melez)",
    "Kıl Keçisi",
    "Saanen",
    "Ankara Keçisi (Tiftik)",
    "Halep Keçisi (Damascus/Şami)",
    "Kilis Keçisi",
    "Honamlı",
    "Norduz Keçisi",
    "Gürcü Keçisi",
    "Malta Keçisi",
    "Alpin (Alpine)",
    "Toggenburg",
    "Boer",
    "Nubian (Anglo-Nubian)",
    "Kaşmir",
    "LaMancha",
    "Nijerya Cücesi (Nigerian Dwarf)",
    "Pigme Keçisi",
  ],
  EXOTIC: [
    "Pigme Kirpisi (African Pygmy Hedgehog)",
    "Şeker Planörü (Sugar Glider)",
    "Tarantula",
    "Akrep",
    "Çubuk Böceği",
    "Dev Afrika Salyangozu",
    "Mini Domuz (Minipig)",
    "Alpaka",
    "Lama",
    "Kinkajou",
    "Kokarca (Skunk)",
    "Rakun",
    "Fennek Tilkisi",
    "Serval",
  ],
  OTHER: [],
};
