// Clinical vocabulary for the treatment and diagnostic forms.
//
// Turkish-first, grouped the way veterinary teams think about their work,
// so the searchable combobox offers the right term after two or three
// keystrokes. Both fields stay free text: anything not listed can be typed
// and is saved as-is.

export const TREATMENTS: readonly string[] = [
  // Koruyucu hekimlik
  "İç parazit uygulaması (antelmintik)",
  "Dış parazit uygulaması (ektoparaziter)",
  "Kene çıkarma",
  "Mikroçip uygulaması",
  "Tırnak kesimi",
  "Kulak temizliği",
  "Anal bez boşaltma",
  "Tıbbi tıraş",
  // Uygulamalar
  "Subkutan enjeksiyon (SC)",
  "İntramüsküler enjeksiyon (IM)",
  "İntravenöz enjeksiyon (IV)",
  "Subkutan sıvı tedavisi",
  "İntravenöz sıvı tedavisi (serum)",
  "Kan alma",
  "Kan transfüzyonu",
  "Oksijen tedavisi",
  "Nebülizasyon",
  "İdrar sondası uygulaması",
  "Sistosentez",
  "Lavman",
  "Nazogastrik / özofagostomi tüpü uygulaması",
  "Göz yıkama ve topikal uygulama",
  "Kulak yıkama",
  // Yara ve ortopedi
  "Yara temizliği ve pansuman",
  "Yara debridmanı",
  "Sütür (dikiş)",
  "Sütür alımı",
  "Abse drenajı",
  "Bandaj / atel değişimi",
  "Kırık stabilizasyonu (atel / alçı)",
  "Ortopedik cerrahi (osteosentez)",
  "Çapraz bağ operasyonu (TPLO / ekstrakapsüler)",
  "Patella luksasyonu operasyonu",
  "Amputasyon",
  // Yumuşak doku cerrahisi
  "Kısırlaştırma (ovariohisterektomi)",
  "Kastrasyon (orşiektomi)",
  "Sezaryen",
  "Piyometra operasyonu",
  "Yabancı cisim çıkarma (gastrotomi / enterotomi)",
  "Kitle eksizyonu",
  "Fıtık operasyonu (herniorafi)",
  "Sistotomi (mesane taşı)",
  "Splenektomi",
  "Gastropeksi",
  "Kulak kanalı operasyonu (TECA / lateral rezeksiyon)",
  "Göz operasyonu (entropion / ektropion)",
  "Enükleasyon",
  "Cherry eye operasyonu",
  // Diş
  "Diş taşı temizliği (detartraj) ve polisaj",
  "Diş çekimi",
  "Ağız içi muayene (anestezi altında)",
  // Anestezi ve yoğun bakım
  "Sedasyon",
  "Genel anestezi",
  "Hospitalizasyon (yatış)",
  "Yoğun bakım takibi",
  // Üreme
  "Doğum yardımı",
  "Suni tohumlama",
  "Gebelik kontrolü",
  // Diğer
  "Fizyoterapi / rehabilitasyon",
  "Lazer tedavisi",
  "Akupunktur",
  "Kemoterapi uygulaması",
  "Ötanazi",
];

/** Test names keyed by the DiagnosticType enum value. */
export const DIAGNOSTIC_TESTS: Record<string, readonly string[]> = {
  BLOOD: [
    "Tam kan sayımı (hemogram / CBC)",
    "Biyokimya paneli",
    "Karaciğer paneli (ALT, AST, ALP, GGT, bilirubin)",
    "Böbrek paneli (BUN, kreatinin, SDMA, fosfor)",
    "Elektrolit paneli (Na, K, Cl)",
    "Kan gazı analizi",
    "Kan glukozu",
    "Fruktozamin",
    "Total T4",
    "Serbest T4 ve TSH",
    "Kortizol / ACTH stimülasyon testi",
    "Düşük doz deksametazon supresyon testi",
    "Pankreatik lipaz (cPL / fPL)",
    "Koagülasyon profili (PT / aPTT)",
    "Kan grubu tayini",
    "Periferik kan yayması",
    "FeLV / FIV hızlı testi",
    "Parvovirüs hızlı testi",
    "Distemper hızlı testi",
    "Corona hızlı testi",
    "Giardia hızlı testi",
    "Dirofilaria (kalp kurdu) antijen testi",
    "Leishmania antikor testi",
    "Ehrlichia / Anaplasma / Borrelia (4Dx)",
    "Toksoplazma serolojisi",
    "Progesteron",
    "Relaksin (gebelik) testi",
    "Alerji paneli (IgE)",
    "NT-proBNP (kardiyak)",
  ],
  URINE: [
    "Tam idrar analizi",
    "İdrar dansitesi (refraktometre)",
    "İdrar sedimenti",
    "İdrar protein / kreatinin oranı (UPC)",
    "İdrar kültürü ve antibiyogram",
    "İdrar kortizol / kreatinin oranı",
  ],
  FECAL: [
    "Dışkı flotasyon (parazit yumurtası)",
    "Dışkı direkt mikroskopi",
    "Giardia antijen testi (dışkı)",
    "Parvovirüs antijen testi (dışkı)",
    "Dışkı kültürü",
    "Dışkı PCR paneli",
  ],
  CYTOLOGY: [
    "İnce iğne aspirasyon sitolojisi (İİA)",
    "Deri kazıntısı (demodeks / uyuz)",
    "Kulak sitolojisi",
    "Vajinal sitoloji",
    "Efüzyon sitolojisi",
    "Lenf düğümü sitolojisi",
    "Histopatoloji (biyopsi)",
    "Dermatofit muayenesi (KOH)",
  ],
  CULTURE: [
    "Bakteri kültürü ve antibiyogram",
    "Mantar kültürü (DTM)",
    "Kulak kültürü",
    "Yara kültürü",
    "Kan kültürü",
  ],
  XRAY: [
    "Toraks röntgeni (2 yönlü)",
    "Abdomen röntgeni",
    "Ekstremite röntgeni",
    "Pelvis röntgeni (kalça displazisi)",
    "Omurga röntgeni",
    "Kafa ve diş röntgeni",
    "Kontrastlı röntgen (baryum)",
  ],
  ULTRASOUND: [
    "Abdominal ultrason",
    "Gebelik ultrasonu",
    "Ekokardiyografi",
    "Üriner sistem ultrasonu",
    "Ultrason eşliğinde biyopsi / aspirasyon",
    "Göz ultrasonu",
  ],
  MRI: ["Beyin MR", "Omurga MR", "Eklem MR"],
  CT: ["Bilgisayarlı tomografi (BT)", "Kontrastlı BT", "BT anjiyografi"],
  ECG: ["EKG", "Holter EKG", "Kan basıncı ölçümü (Doppler / osilometrik)"],
  ENDOSCOPY: ["Gastroskopi", "Kolonoskopi", "Rinoskopi", "Bronkoskopi", "Otoskopi", "Artroskopi"],
  OTHER: [
    "Tonometri (göz içi basıncı)",
    "Schirmer gözyaşı testi",
    "Floresein boyama testi",
    "Wood lambası muayenesi",
    "Trichogram (kıl muayenesi)",
    "PCR paneli",
    "Genetik test",
    "Nekropsi",
  ],
};

// Vaccines a Turkish small-animal clinic gives, with the trade names staff
// actually say in brackets so either spelling finds the row. Free text as
// well: a product not listed is typed and saved as-is.
export const VACCINES: readonly string[] = [
  // Köpek
  "Kuduz (Rabies)",
  "Karma - Parvo, Gençlik, Hepatit, Parainfluenza (DHPPi)",
  "Karma + Leptospiroz (DHPPi+L)",
  "Parvovirüs",
  "Gençlik hastalığı (Distemper)",
  "Leptospiroz",
  "Bronchiseptica / Köpek öksürüğü (Kennel cough)",
  "Coronavirüs",
  "Leishmania",
  // Kedi
  "Kedi karma - Panlökopeni, Rinotrakeit, Kalisi (FVRCP)",
  "Kedi karma + Klamidya (FVRCP+C)",
  "Kedi lösemisi (FeLV)",
  "Kedi enfeksiyöz peritoniti (FIP)",
  // Diğer türler
  "Tavşan - Myxomatosis / RHD",
  "Gelincik - Gençlik hastalığı (Distemper)",
  "At - Tetanoz",
  "At - İnfluenza",
  "Büyükbaş - Şap",
  "Büyükbaş - Brusella",
  "Küçükbaş - Enterotoksemi",
  "Küçükbaş - Çiçek",
];
